site_name: EE579 Group 4 Docs
repo_url: https://github.com/fraserb99/ee579-docs
edit_uri: edit/main/docs/

nav:
    - Home: index.md
    - For Developers:
      - Registering a Device: register-device.md
      - Connecting to the broker: mqtt.md
      - Messaging Schema: mqtt-schema.md
      - Web Hooks: webhooks.md
    - For Users:
      - Creating an Account: create-account.md
      - Multi-Tenancy: multi-tenancy.md
      - Managing Users: users.md
      - Managing Devices: devices.md
      - Rules: rules.md
    - For Maintainers:
      - API: api.md
theme: material

markdown_extensions:
    - toc:
        permalink: "#"
    - fenced_code
    - pymdownx.highlight
    - pymdownx.superfences

plugins:
    - search
    # - pdf-export:
    #     combined: true